# Generated by Django 5.2.8 on 2026-01-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StegoStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('operation', models.CharField(choices=[('ENCODE', 'Encoding'), ('DECODE', 'Decoding')], max_length=10)),
                ('image_size_bytes', models.IntegerField()),
                ('message_length', models.IntegerField(default=0)),
                ('psnr', models.FloatField(blank=True, null=True)),
                ('mse', models.FloatField(blank=True, null=True)),
                ('processing_time_ms', models.FloatField()),
                ('success', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
